version: "3"
services:
  nginx:
    image: nginx:1.15
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/usr/share/nginx/html
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: gazou_mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      # - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Tokyo
  phpmyadmin:
    container_name: gazou_phpmyadmin
    restart: always
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
    depends_on:
      - ${PMA_DB_ENGINE}

volumes:
  db_volume:
